import ThemeScript from 'lib/ThemeScript';

import { robotoMono, sharpGrotesk, sharpSans } from 'assets/fonts';

import Footer from 'global/footer';
import Header from 'global/header';

import { cx } from 'theme/css';

import type { Metadata } from 'next';

import 'app/(app)/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en" suppressHydrationWarning>
    <head>
      <ThemeScript />
    </head>
    <body className={cx(sharpGrotesk.variable, sharpSans.variable, robotoMono.variable)}>
      <Header />
      {children}
      <Footer />
    </body>
  </html>
);

export default RootLayout;
