import ThemeScript from 'lib/ThemeScript';

import { robotoMono, sharpGrotesk, sharpSans } from 'assets/fonts';

import { cx } from 'theme/css';

import Footer from 'layout/footer';
import Header from 'layout/header';

import type { Metadata } from 'next';

import 'app/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang='en'>
    <head>
      <ThemeScript />
    </head>
    <body
      className={cx(
        sharpGrotesk.variable,
        sharpSans.variable,
        robotoMono.variable
      )}
    >
      <Header />
      <main>{children}</main>
      <Footer />
    </body>
  </html>
);

export default RootLayout;
